		.area ROM
		.word enable
		.word disable
		.word permit
		.word forbid
		.word sysopen
		.word sysclose
		.word sysread
		.word syswrite
		.word sysseek
		.word syscontrol
		.word getnextdirent
		.word opencwd
		.word findinode
		.word openfile
		.word closefile
		.word statfile
		.word statopenfile
		.word typeopenfile
		.word changecwd
		.word initlist
		.word addhead
		.word addtail
		.word remhead
		.word remtail
		.word remove
		.word memoryavail
		.word memoryalloc
		.word memoryfree
		.word createtask
		.word newtask
		.word exittask
		.word childexit
		.word runchild
		.word settaskname
		.word signalalloc
		.word signalfree
		.word wait
		.word signal
		.word mountminix
		.word unmountminix
		.word readfsblock
		.word getinode
		.word handleioerror
		.word getchardefio
		.word getchar
		.word putchardefio
		.word putchar
		.word getchars
		.word putstrdefio
		.word putstr
		.word getstrdefio
		.word getstr
		.word putbytedefio
		.word putbyte
		.word putbytebdefio
		.word putbyteb
		.word putworddefio
		.word putword
		.word putlabwdefio
		.word putlabw
		.word putlabbdefio
		.word putlabb
		.word putlabbbdefio
		.word putlabbb
		.word bytetoaschex
		.word wordtoaschex
		.word copystr
		.word strcmp
		.word parseinput
		.word printableasc
		.word toupper
		.word strmatcharray
		.word vindirect
		.word vsetcolour
		.word vsetcolours
		.word vinit
		.word vwrite
		.word vclear
		.word vread
		.word vseekwrite
		.word vseekread
		.word geterrorstr
		.word delay
		.word swapword
		.word swaplong
		.word div32
		.word mul32
		.word memcpy256
