; contains scancode constants

KEY_ESCAPE	.equ 0x00

KEY_F1		.equ 0x02
KEY_F2		.equ 0x03
KEY_F3		.equ 0x04
KEY_F4		.equ 0x05
KEY_F5		.equ 0x06
KEY_F6		.equ 0x08
KEY_F7		.equ 0x0a
KEY_F8		.equ 0x0b
KEY_F9		.equ 0x0c
KEY_F10		.equ 0x0d

KEY_HELP	.equ 0x0e

KEY_TAB		.equ 0x20
KEY_RETURN	.equ 0x2d
KEY_DELETE	.equ 0x3d
KEY_BACKSPACE	.equ 0x4d

KEY_UP		.equ 0x1e
KEY_LEFT	.equ 0x2e
KEY_RIGHT	.equ 0x3e
KEY_DOWN	.equ 0x4e

KEY_CAPS_LOCK	.equ 0x30

KEY_R_SHIFT	.equ 0x50
KEY_R_ALT	.equ 0x51
KEY_R_AMGIGA	.equ 0x52
KEY_CTRL	.equ 0x53
KEY_L_SHIFT	.equ 0x54
KEY_L_ALT	.equ 0x55
KEY_L_AMIGA	.equ 0x56
